TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devVGC501.db
DB += devVGC501Gauge.db
DB += $(TOP)/VGC501Sup/devVGC501.proto

#=======================================
include $(TOP)/configure/RULES
